//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:21 PM MSD 
//


package org.adlnet.xsd.adlseq_v1p3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for constrainChoiceConsiderationsType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="constrainChoiceConsiderationsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="preventActivation" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="constrainChoice" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "constrainChoiceConsiderationsType")
public class ConstrainChoiceConsiderationsType {

    @XmlAttribute
    protected Boolean preventActivation;
    @XmlAttribute
    protected Boolean constrainChoice;

    /**
     * Gets the value of the preventActivation property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isPreventActivation() {
        if (preventActivation == null) {
            return false;
        } else {
            return preventActivation;
        }
    }

    /**
     * Sets the value of the preventActivation property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setPreventActivation(Boolean value) {
        this.preventActivation = value;
    }

    /**
     * Gets the value of the constrainChoice property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isConstrainChoice() {
        if (constrainChoice == null) {
            return false;
        } else {
            return constrainChoice;
        }
    }

    /**
     * Sets the value of the constrainChoice property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setConstrainChoice(Boolean value) {
        this.constrainChoice = value;
    }

}
