//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:21 PM MSD 
//


package org.adlnet.xsd.adlseq_v1p3;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for mapInfoType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="mapInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="targetObjectiveID" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="readRawScore" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="readMinScore" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="readMaxScore" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="readCompletionStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="readProgressMeasure" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="writeRawScore" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="writeMinScore" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="writeMaxScore" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="writeCompletionStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="writeProgressMeasure" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mapInfoType")
public class MapInfoType {

    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String targetObjectiveID;
    @XmlAttribute
    protected Boolean readRawScore;
    @XmlAttribute
    protected Boolean readMinScore;
    @XmlAttribute
    protected Boolean readMaxScore;
    @XmlAttribute
    protected Boolean readCompletionStatus;
    @XmlAttribute
    protected Boolean readProgressMeasure;
    @XmlAttribute
    protected Boolean writeRawScore;
    @XmlAttribute
    protected Boolean writeMinScore;
    @XmlAttribute
    protected Boolean writeMaxScore;
    @XmlAttribute
    protected Boolean writeCompletionStatus;
    @XmlAttribute
    protected Boolean writeProgressMeasure;

    /**
     * Gets the value of the targetObjectiveID property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getTargetObjectiveID() {
        return targetObjectiveID;
    }

    /**
     * Sets the value of the targetObjectiveID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTargetObjectiveID(String value) {
        this.targetObjectiveID = value;
    }

    /**
     * Gets the value of the readRawScore property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isReadRawScore() {
        if (readRawScore == null) {
            return true;
        } else {
            return readRawScore;
        }
    }

    /**
     * Sets the value of the readRawScore property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setReadRawScore(Boolean value) {
        this.readRawScore = value;
    }

    /**
     * Gets the value of the readMinScore property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isReadMinScore() {
        if (readMinScore == null) {
            return true;
        } else {
            return readMinScore;
        }
    }

    /**
     * Sets the value of the readMinScore property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setReadMinScore(Boolean value) {
        this.readMinScore = value;
    }

    /**
     * Gets the value of the readMaxScore property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isReadMaxScore() {
        if (readMaxScore == null) {
            return true;
        } else {
            return readMaxScore;
        }
    }

    /**
     * Sets the value of the readMaxScore property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setReadMaxScore(Boolean value) {
        this.readMaxScore = value;
    }

    /**
     * Gets the value of the readCompletionStatus property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isReadCompletionStatus() {
        if (readCompletionStatus == null) {
            return true;
        } else {
            return readCompletionStatus;
        }
    }

    /**
     * Sets the value of the readCompletionStatus property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setReadCompletionStatus(Boolean value) {
        this.readCompletionStatus = value;
    }

    /**
     * Gets the value of the readProgressMeasure property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isReadProgressMeasure() {
        if (readProgressMeasure == null) {
            return true;
        } else {
            return readProgressMeasure;
        }
    }

    /**
     * Sets the value of the readProgressMeasure property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setReadProgressMeasure(Boolean value) {
        this.readProgressMeasure = value;
    }

    /**
     * Gets the value of the writeRawScore property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isWriteRawScore() {
        if (writeRawScore == null) {
            return false;
        } else {
            return writeRawScore;
        }
    }

    /**
     * Sets the value of the writeRawScore property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setWriteRawScore(Boolean value) {
        this.writeRawScore = value;
    }

    /**
     * Gets the value of the writeMinScore property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isWriteMinScore() {
        if (writeMinScore == null) {
            return false;
        } else {
            return writeMinScore;
        }
    }

    /**
     * Sets the value of the writeMinScore property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setWriteMinScore(Boolean value) {
        this.writeMinScore = value;
    }

    /**
     * Gets the value of the writeMaxScore property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isWriteMaxScore() {
        if (writeMaxScore == null) {
            return false;
        } else {
            return writeMaxScore;
        }
    }

    /**
     * Sets the value of the writeMaxScore property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setWriteMaxScore(Boolean value) {
        this.writeMaxScore = value;
    }

    /**
     * Gets the value of the writeCompletionStatus property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isWriteCompletionStatus() {
        if (writeCompletionStatus == null) {
            return false;
        } else {
            return writeCompletionStatus;
        }
    }

    /**
     * Sets the value of the writeCompletionStatus property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setWriteCompletionStatus(Boolean value) {
        this.writeCompletionStatus = value;
    }

    /**
     * Gets the value of the writeProgressMeasure property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isWriteProgressMeasure() {
        if (writeProgressMeasure == null) {
            return false;
        } else {
            return writeProgressMeasure;
        }
    }

    /**
     * Sets the value of the writeProgressMeasure property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setWriteProgressMeasure(Boolean value) {
        this.writeProgressMeasure = value;
    }

}
