//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:21 PM MSD 
//


package org.adlnet.xsd.adlseq_v1p3;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.adlnet.xsd.adlseq_v1p3 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MapInfo_QNAME = new QName("http://www.adlnet.org/xsd/adlseq_v1p3", "mapInfo");
    private final static QName _Objectives_QNAME = new QName("http://www.adlnet.org/xsd/adlseq_v1p3", "objectives");
    private final static QName _Objective_QNAME = new QName("http://www.adlnet.org/xsd/adlseq_v1p3", "objective");
    private final static QName _RollupConsiderations_QNAME = new QName("http://www.adlnet.org/xsd/adlseq_v1p3", "rollupConsiderations");
    private final static QName _ConstrainedChoiceConsiderations_QNAME = new QName("http://www.adlnet.org/xsd/adlseq_v1p3", "constrainedChoiceConsiderations");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.adlnet.xsd.adlseq_v1p3
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObjectivesType }
     */
    public ObjectivesType createObjectivesType() {
        return new ObjectivesType();
    }

    /**
     * Create an instance of {@link MapInfoType }
     */
    public MapInfoType createMapInfoType() {
        return new MapInfoType();
    }

    /**
     * Create an instance of {@link ConstrainChoiceConsiderationsType }
     */
    public ConstrainChoiceConsiderationsType createConstrainChoiceConsiderationsType() {
        return new ConstrainChoiceConsiderationsType();
    }

    /**
     * Create an instance of {@link ObjectiveType }
     */
    public ObjectiveType createObjectiveType() {
        return new ObjectiveType();
    }

    /**
     * Create an instance of {@link RollupConsiderationsType }
     */
    public RollupConsiderationsType createRollupConsiderationsType() {
        return new RollupConsiderationsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MapInfoType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlseq_v1p3", name = "mapInfo")
    public JAXBElement<MapInfoType> createMapInfo(MapInfoType value) {
        return new JAXBElement<MapInfoType>(_MapInfo_QNAME, MapInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectivesType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlseq_v1p3", name = "objectives")
    public JAXBElement<ObjectivesType> createObjectives(ObjectivesType value) {
        return new JAXBElement<ObjectivesType>(_Objectives_QNAME, ObjectivesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectiveType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlseq_v1p3", name = "objective")
    public JAXBElement<ObjectiveType> createObjective(ObjectiveType value) {
        return new JAXBElement<ObjectiveType>(_Objective_QNAME, ObjectiveType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RollupConsiderationsType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlseq_v1p3", name = "rollupConsiderations")
    public JAXBElement<RollupConsiderationsType> createRollupConsiderations(RollupConsiderationsType value) {
        return new JAXBElement<RollupConsiderationsType>(_RollupConsiderations_QNAME, RollupConsiderationsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConstrainChoiceConsiderationsType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlseq_v1p3", name = "constrainedChoiceConsiderations")
    public JAXBElement<ConstrainChoiceConsiderationsType> createConstrainedChoiceConsiderations(ConstrainChoiceConsiderationsType value) {
        return new JAXBElement<ConstrainChoiceConsiderationsType>(_ConstrainedChoiceConsiderations_QNAME, ConstrainChoiceConsiderationsType.class, null, value);
    }

}
