//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:21 PM MSD 
//


package org.adlnet.xsd.adlseq_v1p3;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for objectiveType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="objectiveType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.adlnet.org/xsd/adlseq_v1p3}mapInfo" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="objectiveID" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "objectiveType", propOrder = {
        "mapInfo"
})
public class ObjectiveType {

    @XmlElement(required = true)
    protected List<MapInfoType> mapInfo;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String objectiveID;

    /**
     * Gets the value of the mapInfo property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mapInfo property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMapInfo().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link MapInfoType }
     */
    public List<MapInfoType> getMapInfo() {
        if (mapInfo == null) {
            mapInfo = new ArrayList<MapInfoType>();
        }
        return this.mapInfo;
    }

    /**
     * Gets the value of the objectiveID property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getObjectiveID() {
        return objectiveID;
    }

    /**
     * Sets the value of the objectiveID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setObjectiveID(String value) {
        this.objectiveID = value;
    }

}
