//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:21 PM MSD 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.adlnet.org/xsd/adlseq_v1p3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED) package org.adlnet.xsd.adlseq_v1p3;
