//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:21 PM MSD 
//


package org.adlnet.xsd.adlseq_v1p3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rollupConsiderationType.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;simpleType name="rollupConsiderationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="always"/>
 *     &lt;enumeration value="ifAttempted"/>
 *     &lt;enumeration value="ifNotSkipped"/>
 *     &lt;enumeration value="ifNotSuspended"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "rollupConsiderationType")
@XmlEnum
public enum RollupConsiderationType {

    @XmlEnumValue("always")
    ALWAYS("always"),
    @XmlEnumValue("ifAttempted")
    IF_ATTEMPTED("ifAttempted"),
    @XmlEnumValue("ifNotSkipped")
    IF_NOT_SKIPPED("ifNotSkipped"),
    @XmlEnumValue("ifNotSuspended")
    IF_NOT_SUSPENDED("ifNotSuspended");
    private final String value;

    RollupConsiderationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RollupConsiderationType fromValue(String v) {
        for (RollupConsiderationType c : RollupConsiderationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
