//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:21 PM MSD 
//


package org.adlnet.xsd.adlnav_v1p3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hideLMSUIType.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;simpleType name="hideLMSUIType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="abandon"/>
 *     &lt;enumeration value="continue"/>
 *     &lt;enumeration value="exit"/>
 *     &lt;enumeration value="previous"/>
 *     &lt;enumeration value="suspendAll"/>
 *     &lt;enumeration value="exitAll"/>
 *     &lt;enumeration value="abandonAll"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "hideLMSUIType")
@XmlEnum
public enum HideLMSUIType {

    @XmlEnumValue("abandon")
    ABANDON("abandon"),
    @XmlEnumValue("continue")
    CONTINUE("continue"),
    @XmlEnumValue("exit")
    EXIT("exit"),
    @XmlEnumValue("previous")
    PREVIOUS("previous"),
    @XmlEnumValue("suspendAll")
    SUSPEND_ALL("suspendAll"),
    @XmlEnumValue("exitAll")
    EXIT_ALL("exitAll"),
    @XmlEnumValue("abandonAll")
    ABANDON_ALL("abandonAll");
    private final String value;

    HideLMSUIType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HideLMSUIType fromValue(String v) {
        for (HideLMSUIType c : HideLMSUIType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
