//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:21 PM MSD 
//


package org.adlnet.xsd.adlnav_v1p3;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.adlnet.xsd.adlnav_v1p3 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HideLMSUI_QNAME = new QName("http://www.adlnet.org/xsd/adlnav_v1p3", "hideLMSUI");
    private final static QName _Presentation_QNAME = new QName("http://www.adlnet.org/xsd/adlnav_v1p3", "presentation");
    private final static QName _NavigationInterface_QNAME = new QName("http://www.adlnet.org/xsd/adlnav_v1p3", "navigationInterface");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.adlnet.xsd.adlnav_v1p3
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NavigationInterfaceType }
     */
    public NavigationInterfaceType createNavigationInterfaceType() {
        return new NavigationInterfaceType();
    }

    /**
     * Create an instance of {@link PresentationType }
     */
    public PresentationType createPresentationType() {
        return new PresentationType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HideLMSUIType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlnav_v1p3", name = "hideLMSUI")
    public JAXBElement<HideLMSUIType> createHideLMSUI(HideLMSUIType value) {
        return new JAXBElement<HideLMSUIType>(_HideLMSUI_QNAME, HideLMSUIType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PresentationType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlnav_v1p3", name = "presentation")
    public JAXBElement<PresentationType> createPresentation(PresentationType value) {
        return new JAXBElement<PresentationType>(_Presentation_QNAME, PresentationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NavigationInterfaceType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlnav_v1p3", name = "navigationInterface")
    public JAXBElement<NavigationInterfaceType> createNavigationInterface(NavigationInterfaceType value) {
        return new JAXBElement<NavigationInterfaceType>(_NavigationInterface_QNAME, NavigationInterfaceType.class, null, value);
    }

}
