//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:21 PM MSD 
//


package org.adlnet.xsd.adlnav_v1p3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for presentationType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="presentationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.adlnet.org/xsd/adlnav_v1p3}navigationInterface" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "presentationType", propOrder = {
        "navigationInterface"
})
public class PresentationType {

    protected NavigationInterfaceType navigationInterface;

    /**
     * Gets the value of the navigationInterface property.
     *
     * @return possible object is
     *         {@link NavigationInterfaceType }
     */
    public NavigationInterfaceType getNavigationInterface() {
        return navigationInterface;
    }

    /**
     * Sets the value of the navigationInterface property.
     *
     * @param value allowed object is
     *              {@link NavigationInterfaceType }
     */
    public void setNavigationInterface(NavigationInterfaceType value) {
        this.navigationInterface = value;
    }

}
