//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:22 PM MSD 
//


package org.imsglobal.xsd.imsss;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for auxiliaryResourceType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="auxiliaryResourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="auxiliaryResourceID" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="purpose" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "auxiliaryResourceType")
public class AuxiliaryResourceType {

    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String auxiliaryResourceID;
    @XmlAttribute(required = true)
    protected String purpose;

    /**
     * Gets the value of the auxiliaryResourceID property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAuxiliaryResourceID() {
        return auxiliaryResourceID;
    }

    /**
     * Sets the value of the auxiliaryResourceID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAuxiliaryResourceID(String value) {
        this.auxiliaryResourceID = value;
    }

    /**
     * Gets the value of the purpose property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPurpose(String value) {
        this.purpose = value;
    }

}
