//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:22 PM MSD 
//


package org.imsglobal.xsd.imsss;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for childActivityType.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;simpleType name="childActivityType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="all"/>
 *     &lt;enumeration value="any"/>
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="atLeastCount"/>
 *     &lt;enumeration value="atLeastPercent"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "childActivityType")
@XmlEnum
public enum ChildActivityType {

    @XmlEnumValue("all")
    ALL("all"),
    @XmlEnumValue("any")
    ANY("any"),
    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("atLeastCount")
    AT_LEAST_COUNT("atLeastCount"),
    @XmlEnumValue("atLeastPercent")
    AT_LEAST_PERCENT("atLeastPercent");
    private final String value;

    ChildActivityType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ChildActivityType fromValue(String v) {
        for (ChildActivityType c : ChildActivityType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
