//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:22 PM MSD 
//


package org.imsglobal.xsd.imsss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * The type that describes any element which fullfills a delivery control semantic
 * <p/>
 * <p>Java class for deliveryControlsType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="deliveryControlsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="tracked" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="completionSetByContent" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="objectiveSetByContent" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deliveryControlsType")
public class DeliveryControlsType {

    @XmlAttribute
    protected Boolean tracked;
    @XmlAttribute
    protected Boolean completionSetByContent;
    @XmlAttribute
    protected Boolean objectiveSetByContent;

    /**
     * Gets the value of the tracked property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isTracked() {
        if (tracked == null) {
            return true;
        } else {
            return tracked;
        }
    }

    /**
     * Sets the value of the tracked property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setTracked(Boolean value) {
        this.tracked = value;
    }

    /**
     * Gets the value of the completionSetByContent property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isCompletionSetByContent() {
        if (completionSetByContent == null) {
            return false;
        } else {
            return completionSetByContent;
        }
    }

    /**
     * Sets the value of the completionSetByContent property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setCompletionSetByContent(Boolean value) {
        this.completionSetByContent = value;
    }

    /**
     * Gets the value of the objectiveSetByContent property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isObjectiveSetByContent() {
        if (objectiveSetByContent == null) {
            return false;
        } else {
            return objectiveSetByContent;
        }
    }

    /**
     * Sets the value of the objectiveSetByContent property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setObjectiveSetByContent(Boolean value) {
        this.objectiveSetByContent = value;
    }

}
