//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:22 PM MSD 
//


package org.imsglobal.xsd.imsss;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;


/**
 * <p>Java class for limitConditionsType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="limitConditionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="attemptLimit" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="attemptAbsoluteDurationLimit" type="{http://www.w3.org/2001/XMLSchema}duration" />
 *       &lt;attribute name="attemptExperiencedDurationLimit" type="{http://www.w3.org/2001/XMLSchema}duration" />
 *       &lt;attribute name="activityAbsoluteDurationLimit" type="{http://www.w3.org/2001/XMLSchema}duration" />
 *       &lt;attribute name="activityExperiencedDurationLimit" type="{http://www.w3.org/2001/XMLSchema}duration" />
 *       &lt;attribute name="beginTimeLimit" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="endTimeLimit" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "limitConditionsType")
public class LimitConditionsType {

    @XmlAttribute
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger attemptLimit;
    @XmlAttribute
    protected Duration attemptAbsoluteDurationLimit;
    @XmlAttribute
    protected Duration attemptExperiencedDurationLimit;
    @XmlAttribute
    protected Duration activityAbsoluteDurationLimit;
    @XmlAttribute
    protected Duration activityExperiencedDurationLimit;
    @XmlAttribute
    protected XMLGregorianCalendar beginTimeLimit;
    @XmlAttribute
    protected XMLGregorianCalendar endTimeLimit;

    /**
     * Gets the value of the attemptLimit property.
     *
     * @return possible object is
     *         {@link BigInteger }
     */
    public BigInteger getAttemptLimit() {
        return attemptLimit;
    }

    /**
     * Sets the value of the attemptLimit property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setAttemptLimit(BigInteger value) {
        this.attemptLimit = value;
    }

    /**
     * Gets the value of the attemptAbsoluteDurationLimit property.
     *
     * @return possible object is
     *         {@link Duration }
     */
    public Duration getAttemptAbsoluteDurationLimit() {
        return attemptAbsoluteDurationLimit;
    }

    /**
     * Sets the value of the attemptAbsoluteDurationLimit property.
     *
     * @param value allowed object is
     *              {@link Duration }
     */
    public void setAttemptAbsoluteDurationLimit(Duration value) {
        this.attemptAbsoluteDurationLimit = value;
    }

    /**
     * Gets the value of the attemptExperiencedDurationLimit property.
     *
     * @return possible object is
     *         {@link Duration }
     */
    public Duration getAttemptExperiencedDurationLimit() {
        return attemptExperiencedDurationLimit;
    }

    /**
     * Sets the value of the attemptExperiencedDurationLimit property.
     *
     * @param value allowed object is
     *              {@link Duration }
     */
    public void setAttemptExperiencedDurationLimit(Duration value) {
        this.attemptExperiencedDurationLimit = value;
    }

    /**
     * Gets the value of the activityAbsoluteDurationLimit property.
     *
     * @return possible object is
     *         {@link Duration }
     */
    public Duration getActivityAbsoluteDurationLimit() {
        return activityAbsoluteDurationLimit;
    }

    /**
     * Sets the value of the activityAbsoluteDurationLimit property.
     *
     * @param value allowed object is
     *              {@link Duration }
     */
    public void setActivityAbsoluteDurationLimit(Duration value) {
        this.activityAbsoluteDurationLimit = value;
    }

    /**
     * Gets the value of the activityExperiencedDurationLimit property.
     *
     * @return possible object is
     *         {@link Duration }
     */
    public Duration getActivityExperiencedDurationLimit() {
        return activityExperiencedDurationLimit;
    }

    /**
     * Sets the value of the activityExperiencedDurationLimit property.
     *
     * @param value allowed object is
     *              {@link Duration }
     */
    public void setActivityExperiencedDurationLimit(Duration value) {
        this.activityExperiencedDurationLimit = value;
    }

    /**
     * Gets the value of the beginTimeLimit property.
     *
     * @return possible object is
     *         {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getBeginTimeLimit() {
        return beginTimeLimit;
    }

    /**
     * Sets the value of the beginTimeLimit property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setBeginTimeLimit(XMLGregorianCalendar value) {
        this.beginTimeLimit = value;
    }

    /**
     * Gets the value of the endTimeLimit property.
     *
     * @return possible object is
     *         {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getEndTimeLimit() {
        return endTimeLimit;
    }

    /**
     * Sets the value of the endTimeLimit property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setEndTimeLimit(XMLGregorianCalendar value) {
        this.endTimeLimit = value;
    }

}
