//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:22 PM MSD 
//


package org.imsglobal.xsd.imsss;

import javax.xml.bind.annotation.*;


/**
 * The type that describes an individual objective mapping.  Mapping one local objective GUID to one global objective GUID
 * <p/>
 * <p>Java class for objectiveMappingType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="objectiveMappingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="targetObjectiveID" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="readSatisfiedStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="readNormalizedMeasure" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="writeSatisfiedStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="writeNormalizedMeasure" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "objectiveMappingType")
@XmlSeeAlso({
        org.imsglobal.xsd.imsss.ObjectiveType.MapInfo.class
})
public class ObjectiveMappingType {

    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String targetObjectiveID;
    @XmlAttribute
    protected Boolean readSatisfiedStatus;
    @XmlAttribute
    protected Boolean readNormalizedMeasure;
    @XmlAttribute
    protected Boolean writeSatisfiedStatus;
    @XmlAttribute
    protected Boolean writeNormalizedMeasure;

    /**
     * Gets the value of the targetObjectiveID property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getTargetObjectiveID() {
        return targetObjectiveID;
    }

    /**
     * Sets the value of the targetObjectiveID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTargetObjectiveID(String value) {
        this.targetObjectiveID = value;
    }

    /**
     * Gets the value of the readSatisfiedStatus property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isReadSatisfiedStatus() {
        if (readSatisfiedStatus == null) {
            return true;
        } else {
            return readSatisfiedStatus;
        }
    }

    /**
     * Sets the value of the readSatisfiedStatus property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setReadSatisfiedStatus(Boolean value) {
        this.readSatisfiedStatus = value;
    }

    /**
     * Gets the value of the readNormalizedMeasure property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isReadNormalizedMeasure() {
        if (readNormalizedMeasure == null) {
            return true;
        } else {
            return readNormalizedMeasure;
        }
    }

    /**
     * Sets the value of the readNormalizedMeasure property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setReadNormalizedMeasure(Boolean value) {
        this.readNormalizedMeasure = value;
    }

    /**
     * Gets the value of the writeSatisfiedStatus property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isWriteSatisfiedStatus() {
        if (writeSatisfiedStatus == null) {
            return false;
        } else {
            return writeSatisfiedStatus;
        }
    }

    /**
     * Sets the value of the writeSatisfiedStatus property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setWriteSatisfiedStatus(Boolean value) {
        this.writeSatisfiedStatus = value;
    }

    /**
     * Gets the value of the writeNormalizedMeasure property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isWriteNormalizedMeasure() {
        if (writeNormalizedMeasure == null) {
            return false;
        } else {
            return writeNormalizedMeasure;
        }
    }

    /**
     * Sets the value of the writeNormalizedMeasure property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setWriteNormalizedMeasure(Boolean value) {
        this.writeNormalizedMeasure = value;
    }

}
