//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:22 PM MSD 
//


package org.imsglobal.xsd.imsss;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * The specification states: "Each activity must have one and only one objective that contributes to rollup".  The following type describes an unbounded set of elements all named "objective" that do not contribute to rollup, and one element called "primaryObjective" that contributes to rollup.
 * <p/>
 * <p>Java class for objectivesType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="objectivesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="primaryObjective">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.imsglobal.org/xsd/imsss}objectiveType">
 *                 &lt;attribute name="objectiveID" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="objective" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.imsglobal.org/xsd/imsss}objectiveType">
 *                 &lt;attribute name="objectiveID" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "objectivesType", propOrder = {
        "primaryObjective",
        "objective"
})
public class ObjectivesType {

    @XmlElement(required = true)
    protected ObjectivesType.PrimaryObjective primaryObjective;
    protected List<ObjectivesType.Objective> objective;

    /**
     * Gets the value of the primaryObjective property.
     *
     * @return possible object is
     *         {@link ObjectivesType.PrimaryObjective }
     */
    public ObjectivesType.PrimaryObjective getPrimaryObjective() {
        return primaryObjective;
    }

    /**
     * Sets the value of the primaryObjective property.
     *
     * @param value allowed object is
     *              {@link ObjectivesType.PrimaryObjective }
     */
    public void setPrimaryObjective(ObjectivesType.PrimaryObjective value) {
        this.primaryObjective = value;
    }

    /**
     * Gets the value of the objective property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objective property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjective().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectivesType.Objective }
     */
    public List<ObjectivesType.Objective> getObjective() {
        if (objective == null) {
            objective = new ArrayList<ObjectivesType.Objective>();
        }
        return this.objective;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.imsglobal.org/xsd/imsss}objectiveType">
     *       &lt;attribute name="objectiveID" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Objective
            extends ObjectiveType {

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String objectiveID;

        /**
         * Gets the value of the objectiveID property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getObjectiveID() {
            return objectiveID;
        }

        /**
         * Sets the value of the objectiveID property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setObjectiveID(String value) {
            this.objectiveID = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.imsglobal.org/xsd/imsss}objectiveType">
     *       &lt;attribute name="objectiveID" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PrimaryObjective
            extends ObjectiveType {

        @XmlAttribute
        @XmlSchemaType(name = "anyURI")
        protected String objectiveID;

        /**
         * Gets the value of the objectiveID property.
         *
         * @return possible object is
         *         {@link String }
         */
        public String getObjectiveID() {
            return objectiveID;
        }

        /**
         * Sets the value of the objectiveID property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setObjectiveID(String value) {
            this.objectiveID = value;
        }

    }

}
