//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:22 PM MSD 
//


package org.imsglobal.xsd.imsss;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for objectiveType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="objectiveType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="minNormalizedMeasure" type="{http://www.imsglobal.org/xsd/imsss}measureType" minOccurs="0"/>
 *         &lt;element name="mapInfo" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.imsglobal.org/xsd/imsss}objectiveMappingType">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="satisfiedByMeasure" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "objectiveType", propOrder = {
        "minNormalizedMeasure",
        "mapInfo"
})
@XmlSeeAlso({
        org.imsglobal.xsd.imsss.ObjectivesType.PrimaryObjective.class,
        org.imsglobal.xsd.imsss.ObjectivesType.Objective.class
})
public class ObjectiveType {

    @XmlElement(defaultValue = "1.00000")
    protected BigDecimal minNormalizedMeasure;
    protected List<ObjectiveType.MapInfo> mapInfo;
    @XmlAttribute
    protected Boolean satisfiedByMeasure;

    /**
     * Gets the value of the minNormalizedMeasure property.
     *
     * @return possible object is
     *         {@link BigDecimal }
     */
    public BigDecimal getMinNormalizedMeasure() {
        return minNormalizedMeasure;
    }

    /**
     * Sets the value of the minNormalizedMeasure property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setMinNormalizedMeasure(BigDecimal value) {
        this.minNormalizedMeasure = value;
    }

    /**
     * Gets the value of the mapInfo property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mapInfo property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMapInfo().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectiveType.MapInfo }
     */
    public List<ObjectiveType.MapInfo> getMapInfo() {
        if (mapInfo == null) {
            mapInfo = new ArrayList<ObjectiveType.MapInfo>();
        }
        return this.mapInfo;
    }

    /**
     * Gets the value of the satisfiedByMeasure property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isSatisfiedByMeasure() {
        if (satisfiedByMeasure == null) {
            return false;
        } else {
            return satisfiedByMeasure;
        }
    }

    /**
     * Sets the value of the satisfiedByMeasure property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setSatisfiedByMeasure(Boolean value) {
        this.satisfiedByMeasure = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.imsglobal.org/xsd/imsss}objectiveMappingType">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class MapInfo
            extends ObjectiveMappingType {


    }

}
