//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:22 PM MSD 
//


package org.imsglobal.xsd.imsss;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.imsglobal.xsd.imsss package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Sequencing_QNAME = new QName("http://www.imsglobal.org/xsd/imsss", "sequencing");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.imsglobal.xsd.imsss
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RollupRuleType.RollupConditions.RollupCondition }
     */
    public RollupRuleType.RollupConditions.RollupCondition createRollupRuleTypeRollupConditionsRollupCondition() {
        return new RollupRuleType.RollupConditions.RollupCondition();
    }

    /**
     * Create an instance of {@link SequencingType }
     */
    public SequencingType createSequencingType() {
        return new SequencingType();
    }

    /**
     * Create an instance of {@link PostConditionRuleType }
     */
    public PostConditionRuleType createPostConditionRuleType() {
        return new PostConditionRuleType();
    }

    /**
     * Create an instance of {@link ObjectivesType }
     */
    public ObjectivesType createObjectivesType() {
        return new ObjectivesType();
    }

    /**
     * Create an instance of {@link RollupRuleType }
     */
    public RollupRuleType createRollupRuleType() {
        return new RollupRuleType();
    }

    /**
     * Create an instance of {@link AuxiliaryResourcesType }
     */
    public AuxiliaryResourcesType createAuxiliaryResourcesType() {
        return new AuxiliaryResourcesType();
    }

    /**
     * Create an instance of {@link SequencingCollection }
     */
    public SequencingCollection createSequencingCollection() {
        return new SequencingCollection();
    }

    /**
     * Create an instance of {@link org.imsglobal.xsd.imsss.SequencingRuleType.RuleConditions.RuleCondition }
     */
    public org.imsglobal.xsd.imsss.SequencingRuleType.RuleConditions.RuleCondition createSequencingRuleTypeRuleConditionsRuleCondition() {
        return new org.imsglobal.xsd.imsss.SequencingRuleType.RuleConditions.RuleCondition();
    }

    /**
     * Create an instance of {@link AuxiliaryResourceType }
     */
    public AuxiliaryResourceType createAuxiliaryResourceType() {
        return new AuxiliaryResourceType();
    }

    /**
     * Create an instance of {@link ControlModeType }
     */
    public ControlModeType createControlModeType() {
        return new ControlModeType();
    }

    /**
     * Create an instance of {@link ObjectivesType.PrimaryObjective }
     */
    public ObjectivesType.PrimaryObjective createObjectivesTypePrimaryObjective() {
        return new ObjectivesType.PrimaryObjective();
    }

    /**
     * Create an instance of {@link ObjectivesType.Objective }
     */
    public ObjectivesType.Objective createObjectivesTypeObjective() {
        return new ObjectivesType.Objective();
    }

    /**
     * Create an instance of {@link RollupRuleType.RollupAction }
     */
    public RollupRuleType.RollupAction createRollupRuleTypeRollupAction() {
        return new RollupRuleType.RollupAction();
    }

    /**
     * Create an instance of {@link RandomizationType }
     */
    public RandomizationType createRandomizationType() {
        return new RandomizationType();
    }

    /**
     * Create an instance of {@link SequencingRulesType }
     */
    public SequencingRulesType createSequencingRulesType() {
        return new SequencingRulesType();
    }

    /**
     * Create an instance of {@link ExitConditionRuleType.RuleAction }
     */
    public ExitConditionRuleType.RuleAction createExitConditionRuleTypeRuleAction() {
        return new ExitConditionRuleType.RuleAction();
    }

    /**
     * Create an instance of {@link PreConditionRuleType }
     */
    public PreConditionRuleType createPreConditionRuleType() {
        return new PreConditionRuleType();
    }

    /**
     * Create an instance of {@link ExitConditionRuleType }
     */
    public ExitConditionRuleType createExitConditionRuleType() {
        return new ExitConditionRuleType();
    }

    /**
     * Create an instance of {@link DeliveryControlsType }
     */
    public DeliveryControlsType createDeliveryControlsType() {
        return new DeliveryControlsType();
    }

    /**
     * Create an instance of {@link ObjectiveMappingType }
     */
    public ObjectiveMappingType createObjectiveMappingType() {
        return new ObjectiveMappingType();
    }

    /**
     * Create an instance of {@link PostConditionRuleType.RuleAction }
     */
    public PostConditionRuleType.RuleAction createPostConditionRuleTypeRuleAction() {
        return new PostConditionRuleType.RuleAction();
    }

    /**
     * Create an instance of {@link RollupRuleType.RollupConditions }
     */
    public RollupRuleType.RollupConditions createRollupRuleTypeRollupConditions() {
        return new RollupRuleType.RollupConditions();
    }

    /**
     * Create an instance of {@link ObjectiveType.MapInfo }
     */
    public ObjectiveType.MapInfo createObjectiveTypeMapInfo() {
        return new ObjectiveType.MapInfo();
    }

    /**
     * Create an instance of {@link ObjectiveType }
     */
    public ObjectiveType createObjectiveType() {
        return new ObjectiveType();
    }

    /**
     * Create an instance of {@link RollupRulesType }
     */
    public RollupRulesType createRollupRulesType() {
        return new RollupRulesType();
    }

    /**
     * Create an instance of {@link org.imsglobal.xsd.imsss.SequencingRuleType.RuleConditions }
     */
    public org.imsglobal.xsd.imsss.SequencingRuleType.RuleConditions createSequencingRuleTypeRuleConditions() {
        return new org.imsglobal.xsd.imsss.SequencingRuleType.RuleConditions();
    }

    /**
     * Create an instance of {@link PreConditionRuleType.RuleAction }
     */
    public PreConditionRuleType.RuleAction createPreConditionRuleTypeRuleAction() {
        return new PreConditionRuleType.RuleAction();
    }

    /**
     * Create an instance of {@link LimitConditionsType }
     */
    public LimitConditionsType createLimitConditionsType() {
        return new LimitConditionsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SequencingType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsss", name = "sequencing")
    public JAXBElement<SequencingType> createSequencing(SequencingType value) {
        return new JAXBElement<SequencingType>(_Sequencing_QNAME, SequencingType.class, null, value);
    }

}
