//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:22 PM MSD 
//


package org.imsglobal.xsd.imsss;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for postConditionRuleActionType.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;simpleType name="postConditionRuleActionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="exitParent"/>
 *     &lt;enumeration value="exitAll"/>
 *     &lt;enumeration value="retry"/>
 *     &lt;enumeration value="retryAll"/>
 *     &lt;enumeration value="continue"/>
 *     &lt;enumeration value="previous"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "postConditionRuleActionType")
@XmlEnum
public enum PostConditionRuleActionType {

    @XmlEnumValue("exitParent")
    EXIT_PARENT("exitParent"),
    @XmlEnumValue("exitAll")
    EXIT_ALL("exitAll"),
    @XmlEnumValue("retry")
    RETRY("retry"),
    @XmlEnumValue("retryAll")
    RETRY_ALL("retryAll"),
    @XmlEnumValue("continue")
    CONTINUE("continue"),
    @XmlEnumValue("previous")
    PREVIOUS("previous");
    private final String value;

    PostConditionRuleActionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PostConditionRuleActionType fromValue(String v) {
        for (PostConditionRuleActionType c : PostConditionRuleActionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
