//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:22 PM MSD 
//


package org.imsglobal.xsd.imsss;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for preConditionRuleActionType.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;simpleType name="preConditionRuleActionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="skip"/>
 *     &lt;enumeration value="disabled"/>
 *     &lt;enumeration value="hiddenFromChoice"/>
 *     &lt;enumeration value="stopForwardTraversal"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "preConditionRuleActionType")
@XmlEnum
public enum PreConditionRuleActionType {

    @XmlEnumValue("skip")
    SKIP("skip"),
    @XmlEnumValue("disabled")
    DISABLED("disabled"),
    @XmlEnumValue("hiddenFromChoice")
    HIDDEN_FROM_CHOICE("hiddenFromChoice"),
    @XmlEnumValue("stopForwardTraversal")
    STOP_FORWARD_TRAVERSAL("stopForwardTraversal");
    private final String value;

    PreConditionRuleActionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PreConditionRuleActionType fromValue(String v) {
        for (PreConditionRuleActionType c : PreConditionRuleActionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
