//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:22 PM MSD 
//


package org.imsglobal.xsd.imsss;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for randomizationType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="randomizationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="randomizationTiming" type="{http://www.imsglobal.org/xsd/imsss}randomTimingType" default="never" />
 *       &lt;attribute name="selectCount" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="reorderChildren" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="selectionTiming" type="{http://www.imsglobal.org/xsd/imsss}randomTimingType" default="never" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "randomizationType")
public class RandomizationType {

    @XmlAttribute
    protected RandomTimingType randomizationTiming;
    @XmlAttribute
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger selectCount;
    @XmlAttribute
    protected Boolean reorderChildren;
    @XmlAttribute
    protected RandomTimingType selectionTiming;

    /**
     * Gets the value of the randomizationTiming property.
     *
     * @return possible object is
     *         {@link RandomTimingType }
     */
    public RandomTimingType getRandomizationTiming() {
        if (randomizationTiming == null) {
            return RandomTimingType.NEVER;
        } else {
            return randomizationTiming;
        }
    }

    /**
     * Sets the value of the randomizationTiming property.
     *
     * @param value allowed object is
     *              {@link RandomTimingType }
     */
    public void setRandomizationTiming(RandomTimingType value) {
        this.randomizationTiming = value;
    }

    /**
     * Gets the value of the selectCount property.
     *
     * @return possible object is
     *         {@link BigInteger }
     */
    public BigInteger getSelectCount() {
        return selectCount;
    }

    /**
     * Sets the value of the selectCount property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setSelectCount(BigInteger value) {
        this.selectCount = value;
    }

    /**
     * Gets the value of the reorderChildren property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isReorderChildren() {
        if (reorderChildren == null) {
            return false;
        } else {
            return reorderChildren;
        }
    }

    /**
     * Sets the value of the reorderChildren property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setReorderChildren(Boolean value) {
        this.reorderChildren = value;
    }

    /**
     * Gets the value of the selectionTiming property.
     *
     * @return possible object is
     *         {@link RandomTimingType }
     */
    public RandomTimingType getSelectionTiming() {
        if (selectionTiming == null) {
            return RandomTimingType.NEVER;
        } else {
            return selectionTiming;
        }
    }

    /**
     * Sets the value of the selectionTiming property.
     *
     * @param value allowed object is
     *              {@link RandomTimingType }
     */
    public void setSelectionTiming(RandomTimingType value) {
        this.selectionTiming = value;
    }

}
