//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:22 PM MSD 
//


package org.imsglobal.xsd.imsss;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for rollupRuleType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="rollupRuleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rollupConditions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rollupCondition" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="operator" type="{http://www.imsglobal.org/xsd/imsss}conditionOperatorType" default="noOp" />
 *                           &lt;attribute name="condition" use="required" type="{http://www.imsglobal.org/xsd/imsss}rollupRuleConditionType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="conditionCombination" type="{http://www.imsglobal.org/xsd/imsss}conditionCombinationType" default="any" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="rollupAction">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="action" use="required" type="{http://www.imsglobal.org/xsd/imsss}rollupActionType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="childActivitySet" type="{http://www.imsglobal.org/xsd/imsss}childActivityType" default="all" />
 *       &lt;attribute name="minimumCount" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
 *       &lt;attribute name="minimumPercent" type="{http://www.imsglobal.org/xsd/imsss}percentType" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rollupRuleType", propOrder = {
        "rollupConditions",
        "rollupAction"
})
public class RollupRuleType {

    @XmlElement(required = true)
    protected RollupRuleType.RollupConditions rollupConditions;
    @XmlElement(required = true)
    protected RollupRuleType.RollupAction rollupAction;
    @XmlAttribute
    protected ChildActivityType childActivitySet;
    @XmlAttribute
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger minimumCount;
    @XmlAttribute
    protected BigDecimal minimumPercent;

    /**
     * Gets the value of the rollupConditions property.
     *
     * @return possible object is
     *         {@link RollupRuleType.RollupConditions }
     */
    public RollupRuleType.RollupConditions getRollupConditions() {
        return rollupConditions;
    }

    /**
     * Sets the value of the rollupConditions property.
     *
     * @param value allowed object is
     *              {@link RollupRuleType.RollupConditions }
     */
    public void setRollupConditions(RollupRuleType.RollupConditions value) {
        this.rollupConditions = value;
    }

    /**
     * Gets the value of the rollupAction property.
     *
     * @return possible object is
     *         {@link RollupRuleType.RollupAction }
     */
    public RollupRuleType.RollupAction getRollupAction() {
        return rollupAction;
    }

    /**
     * Sets the value of the rollupAction property.
     *
     * @param value allowed object is
     *              {@link RollupRuleType.RollupAction }
     */
    public void setRollupAction(RollupRuleType.RollupAction value) {
        this.rollupAction = value;
    }

    /**
     * Gets the value of the childActivitySet property.
     *
     * @return possible object is
     *         {@link ChildActivityType }
     */
    public ChildActivityType getChildActivitySet() {
        if (childActivitySet == null) {
            return ChildActivityType.ALL;
        } else {
            return childActivitySet;
        }
    }

    /**
     * Sets the value of the childActivitySet property.
     *
     * @param value allowed object is
     *              {@link ChildActivityType }
     */
    public void setChildActivitySet(ChildActivityType value) {
        this.childActivitySet = value;
    }

    /**
     * Gets the value of the minimumCount property.
     *
     * @return possible object is
     *         {@link BigInteger }
     */
    public BigInteger getMinimumCount() {
        if (minimumCount == null) {
            return new BigInteger("0");
        } else {
            return minimumCount;
        }
    }

    /**
     * Sets the value of the minimumCount property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setMinimumCount(BigInteger value) {
        this.minimumCount = value;
    }

    /**
     * Gets the value of the minimumPercent property.
     *
     * @return possible object is
     *         {@link BigDecimal }
     */
    public BigDecimal getMinimumPercent() {
        if (minimumPercent == null) {
            return new BigDecimal("0");
        } else {
            return minimumPercent;
        }
    }

    /**
     * Sets the value of the minimumPercent property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setMinimumPercent(BigDecimal value) {
        this.minimumPercent = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="action" use="required" type="{http://www.imsglobal.org/xsd/imsss}rollupActionType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class RollupAction {

        @XmlAttribute(required = true)
        protected RollupActionType action;

        /**
         * Gets the value of the action property.
         *
         * @return possible object is
         *         {@link RollupActionType }
         */
        public RollupActionType getAction() {
            return action;
        }

        /**
         * Sets the value of the action property.
         *
         * @param value allowed object is
         *              {@link RollupActionType }
         */
        public void setAction(RollupActionType value) {
            this.action = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="rollupCondition" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="operator" type="{http://www.imsglobal.org/xsd/imsss}conditionOperatorType" default="noOp" />
     *                 &lt;attribute name="condition" use="required" type="{http://www.imsglobal.org/xsd/imsss}rollupRuleConditionType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="conditionCombination" type="{http://www.imsglobal.org/xsd/imsss}conditionCombinationType" default="any" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "rollupCondition"
    })
    public static class RollupConditions {

        @XmlElement(required = true)
        protected List<RollupRuleType.RollupConditions.RollupCondition> rollupCondition;
        @XmlAttribute
        protected ConditionCombinationType conditionCombination;

        /**
         * Gets the value of the rollupCondition property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rollupCondition property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRollupCondition().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link RollupRuleType.RollupConditions.RollupCondition }
         */
        public List<RollupRuleType.RollupConditions.RollupCondition> getRollupCondition() {
            if (rollupCondition == null) {
                rollupCondition = new ArrayList<RollupRuleType.RollupConditions.RollupCondition>();
            }
            return this.rollupCondition;
        }

        /**
         * Gets the value of the conditionCombination property.
         *
         * @return possible object is
         *         {@link ConditionCombinationType }
         */
        public ConditionCombinationType getConditionCombination() {
            if (conditionCombination == null) {
                return ConditionCombinationType.ANY;
            } else {
                return conditionCombination;
            }
        }

        /**
         * Sets the value of the conditionCombination property.
         *
         * @param value allowed object is
         *              {@link ConditionCombinationType }
         */
        public void setConditionCombination(ConditionCombinationType value) {
            this.conditionCombination = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p/>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p/>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="operator" type="{http://www.imsglobal.org/xsd/imsss}conditionOperatorType" default="noOp" />
         *       &lt;attribute name="condition" use="required" type="{http://www.imsglobal.org/xsd/imsss}rollupRuleConditionType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class RollupCondition {

            @XmlAttribute
            protected ConditionOperatorType operator;
            @XmlAttribute(required = true)
            protected RollupRuleConditionType condition;

            /**
             * Gets the value of the operator property.
             *
             * @return possible object is
             *         {@link ConditionOperatorType }
             */
            public ConditionOperatorType getOperator() {
                if (operator == null) {
                    return ConditionOperatorType.NO_OP;
                } else {
                    return operator;
                }
            }

            /**
             * Sets the value of the operator property.
             *
             * @param value allowed object is
             *              {@link ConditionOperatorType }
             */
            public void setOperator(ConditionOperatorType value) {
                this.operator = value;
            }

            /**
             * Gets the value of the condition property.
             *
             * @return possible object is
             *         {@link RollupRuleConditionType }
             */
            public RollupRuleConditionType getCondition() {
                return condition;
            }

            /**
             * Sets the value of the condition property.
             *
             * @param value allowed object is
             *              {@link RollupRuleConditionType }
             */
            public void setCondition(RollupRuleConditionType value) {
                this.condition = value;
            }

        }

    }

}
