//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:22 PM MSD 
//


package org.imsglobal.xsd.imsss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for rollupRulesType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="rollupRulesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rollupRule" type="{http://www.imsglobal.org/xsd/imsss}rollupRuleType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="rollupObjectiveSatisfied" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="rollupProgressCompletion" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="objectiveMeasureWeight" type="{http://www.imsglobal.org/xsd/imsss}weightType" default="1.0000" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rollupRulesType", propOrder = {
        "rollupRule"
})
public class RollupRulesType {

    protected List<RollupRuleType> rollupRule;
    @XmlAttribute
    protected Boolean rollupObjectiveSatisfied;
    @XmlAttribute
    protected Boolean rollupProgressCompletion;
    @XmlAttribute
    protected BigDecimal objectiveMeasureWeight;

    /**
     * Gets the value of the rollupRule property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rollupRule property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRollupRule().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link RollupRuleType }
     */
    public List<RollupRuleType> getRollupRule() {
        if (rollupRule == null) {
            rollupRule = new ArrayList<RollupRuleType>();
        }
        return this.rollupRule;
    }

    /**
     * Gets the value of the rollupObjectiveSatisfied property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isRollupObjectiveSatisfied() {
        if (rollupObjectiveSatisfied == null) {
            return true;
        } else {
            return rollupObjectiveSatisfied;
        }
    }

    /**
     * Sets the value of the rollupObjectiveSatisfied property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setRollupObjectiveSatisfied(Boolean value) {
        this.rollupObjectiveSatisfied = value;
    }

    /**
     * Gets the value of the rollupProgressCompletion property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isRollupProgressCompletion() {
        if (rollupProgressCompletion == null) {
            return true;
        } else {
            return rollupProgressCompletion;
        }
    }

    /**
     * Sets the value of the rollupProgressCompletion property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setRollupProgressCompletion(Boolean value) {
        this.rollupProgressCompletion = value;
    }

    /**
     * Gets the value of the objectiveMeasureWeight property.
     *
     * @return possible object is
     *         {@link BigDecimal }
     */
    public BigDecimal getObjectiveMeasureWeight() {
        if (objectiveMeasureWeight == null) {
            return new BigDecimal("1.0000");
        } else {
            return objectiveMeasureWeight;
        }
    }

    /**
     * Sets the value of the objectiveMeasureWeight property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setObjectiveMeasureWeight(BigDecimal value) {
        this.objectiveMeasureWeight = value;
    }

}
