//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:22 PM MSD 
//


package org.imsglobal.xsd.imsss;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for sequencingRuleType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="sequencingRuleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ruleConditions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ruleCondition" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="referencedObjective" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                           &lt;attribute name="measureThreshold" type="{http://www.imsglobal.org/xsd/imsss}measureType" />
 *                           &lt;attribute name="operator" type="{http://www.imsglobal.org/xsd/imsss}conditionOperatorType" default="noOp" />
 *                           &lt;attribute name="condition" use="required" type="{http://www.imsglobal.org/xsd/imsss}sequencingRuleConditionType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="conditionCombination" type="{http://www.imsglobal.org/xsd/imsss}conditionCombinationType" default="all" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sequencingRuleType", propOrder = {
        "ruleConditions"
})
@XmlSeeAlso({
        PostConditionRuleType.class,
        ExitConditionRuleType.class,
        PreConditionRuleType.class
})
public abstract class SequencingRuleType {

    protected SequencingRuleType.RuleConditions ruleConditions;

    /**
     * Gets the value of the ruleConditions property.
     *
     * @return possible object is
     *         {@link SequencingRuleType.RuleConditions }
     */
    public SequencingRuleType.RuleConditions getRuleConditions() {
        return ruleConditions;
    }

    /**
     * Sets the value of the ruleConditions property.
     *
     * @param value allowed object is
     *              {@link SequencingRuleType.RuleConditions }
     */
    public void setRuleConditions(SequencingRuleType.RuleConditions value) {
        this.ruleConditions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ruleCondition" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="referencedObjective" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *                 &lt;attribute name="measureThreshold" type="{http://www.imsglobal.org/xsd/imsss}measureType" />
     *                 &lt;attribute name="operator" type="{http://www.imsglobal.org/xsd/imsss}conditionOperatorType" default="noOp" />
     *                 &lt;attribute name="condition" use="required" type="{http://www.imsglobal.org/xsd/imsss}sequencingRuleConditionType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="conditionCombination" type="{http://www.imsglobal.org/xsd/imsss}conditionCombinationType" default="all" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "ruleCondition"
    })
    public static class RuleConditions {

        @XmlElement(required = true)
        protected List<SequencingRuleType.RuleConditions.RuleCondition> ruleCondition;
        @XmlAttribute
        protected ConditionCombinationType conditionCombination;

        /**
         * Gets the value of the ruleCondition property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ruleCondition property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRuleCondition().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link SequencingRuleType.RuleConditions.RuleCondition }
         */
        public List<SequencingRuleType.RuleConditions.RuleCondition> getRuleCondition() {
            if (ruleCondition == null) {
                ruleCondition = new ArrayList<SequencingRuleType.RuleConditions.RuleCondition>();
            }
            return this.ruleCondition;
        }

        /**
         * Gets the value of the conditionCombination property.
         *
         * @return possible object is
         *         {@link ConditionCombinationType }
         */
        public ConditionCombinationType getConditionCombination() {
            if (conditionCombination == null) {
                return ConditionCombinationType.ALL;
            } else {
                return conditionCombination;
            }
        }

        /**
         * Sets the value of the conditionCombination property.
         *
         * @param value allowed object is
         *              {@link ConditionCombinationType }
         */
        public void setConditionCombination(ConditionCombinationType value) {
            this.conditionCombination = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p/>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p/>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="referencedObjective" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *       &lt;attribute name="measureThreshold" type="{http://www.imsglobal.org/xsd/imsss}measureType" />
         *       &lt;attribute name="operator" type="{http://www.imsglobal.org/xsd/imsss}conditionOperatorType" default="noOp" />
         *       &lt;attribute name="condition" use="required" type="{http://www.imsglobal.org/xsd/imsss}sequencingRuleConditionType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class RuleCondition {

            @XmlAttribute
            @XmlSchemaType(name = "anyURI")
            protected String referencedObjective;
            @XmlAttribute
            protected BigDecimal measureThreshold;
            @XmlAttribute
            protected ConditionOperatorType operator;
            @XmlAttribute(required = true)
            protected SequencingRuleConditionType condition;

            /**
             * Gets the value of the referencedObjective property.
             *
             * @return possible object is
             *         {@link String }
             */
            public String getReferencedObjective() {
                return referencedObjective;
            }

            /**
             * Sets the value of the referencedObjective property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setReferencedObjective(String value) {
                this.referencedObjective = value;
            }

            /**
             * Gets the value of the measureThreshold property.
             *
             * @return possible object is
             *         {@link BigDecimal }
             */
            public BigDecimal getMeasureThreshold() {
                return measureThreshold;
            }

            /**
             * Sets the value of the measureThreshold property.
             *
             * @param value allowed object is
             *              {@link BigDecimal }
             */
            public void setMeasureThreshold(BigDecimal value) {
                this.measureThreshold = value;
            }

            /**
             * Gets the value of the operator property.
             *
             * @return possible object is
             *         {@link ConditionOperatorType }
             */
            public ConditionOperatorType getOperator() {
                if (operator == null) {
                    return ConditionOperatorType.NO_OP;
                } else {
                    return operator;
                }
            }

            /**
             * Sets the value of the operator property.
             *
             * @param value allowed object is
             *              {@link ConditionOperatorType }
             */
            public void setOperator(ConditionOperatorType value) {
                this.operator = value;
            }

            /**
             * Gets the value of the condition property.
             *
             * @return possible object is
             *         {@link SequencingRuleConditionType }
             */
            public SequencingRuleConditionType getCondition() {
                return condition;
            }

            /**
             * Sets the value of the condition property.
             *
             * @param value allowed object is
             *              {@link SequencingRuleConditionType }
             */
            public void setCondition(SequencingRuleConditionType value) {
                this.condition = value;
            }

        }

    }

}
