//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:22 PM MSD 
//


package org.imsglobal.xsd.imsss;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for sequencingRulesType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="sequencingRulesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="preConditionRule" type="{http://www.imsglobal.org/xsd/imsss}preConditionRuleType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="exitConditionRule" type="{http://www.imsglobal.org/xsd/imsss}exitConditionRuleType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="postConditionRule" type="{http://www.imsglobal.org/xsd/imsss}postConditionRuleType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sequencingRulesType", propOrder = {
        "preConditionRule",
        "exitConditionRule",
        "postConditionRule"
})
public class SequencingRulesType {

    protected List<PreConditionRuleType> preConditionRule;
    protected List<ExitConditionRuleType> exitConditionRule;
    protected List<PostConditionRuleType> postConditionRule;

    /**
     * Gets the value of the preConditionRule property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the preConditionRule property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreConditionRule().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link PreConditionRuleType }
     */
    public List<PreConditionRuleType> getPreConditionRule() {
        if (preConditionRule == null) {
            preConditionRule = new ArrayList<PreConditionRuleType>();
        }
        return this.preConditionRule;
    }

    /**
     * Gets the value of the exitConditionRule property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exitConditionRule property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExitConditionRule().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link ExitConditionRuleType }
     */
    public List<ExitConditionRuleType> getExitConditionRule() {
        if (exitConditionRule == null) {
            exitConditionRule = new ArrayList<ExitConditionRuleType>();
        }
        return this.exitConditionRule;
    }

    /**
     * Gets the value of the postConditionRule property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the postConditionRule property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPostConditionRule().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link PostConditionRuleType }
     */
    public List<PostConditionRuleType> getPostConditionRule() {
        if (postConditionRule == null) {
            postConditionRule = new ArrayList<PostConditionRuleType>();
        }
        return this.postConditionRule;
    }

}
