//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:22 PM MSD 
//


package org.imsglobal.xsd.imsss;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * The type associated with any top-level sequencing tag
 * <p/>
 * <p>Java class for sequencingType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="sequencingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="controlMode" type="{http://www.imsglobal.org/xsd/imsss}controlModeType" minOccurs="0"/>
 *         &lt;element name="sequencingRules" type="{http://www.imsglobal.org/xsd/imsss}sequencingRulesType" minOccurs="0"/>
 *         &lt;element name="limitConditions" type="{http://www.imsglobal.org/xsd/imsss}limitConditionsType" minOccurs="0"/>
 *         &lt;element name="auxiliaryResources" type="{http://www.imsglobal.org/xsd/imsss}auxiliaryResourcesType" minOccurs="0"/>
 *         &lt;element name="rollupRules" type="{http://www.imsglobal.org/xsd/imsss}rollupRulesType" minOccurs="0"/>
 *         &lt;element name="objectives" type="{http://www.imsglobal.org/xsd/imsss}objectivesType" minOccurs="0"/>
 *         &lt;element name="randomizationControls" type="{http://www.imsglobal.org/xsd/imsss}randomizationType" minOccurs="0"/>
 *         &lt;element name="deliveryControls" type="{http://www.imsglobal.org/xsd/imsss}deliveryControlsType" minOccurs="0"/>
 *         &lt;any/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="IDRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sequencingType", propOrder = {
        "controlMode",
        "sequencingRules",
        "limitConditions",
        "auxiliaryResources",
        "rollupRules",
        "objectives",
        "randomizationControls",
        "deliveryControls",
        "any"
})
public class SequencingType {

    protected ControlModeType controlMode;
    protected SequencingRulesType sequencingRules;
    protected LimitConditionsType limitConditions;
    protected AuxiliaryResourcesType auxiliaryResources;
    protected RollupRulesType rollupRules;
    protected ObjectivesType objectives;
    protected RandomizationType randomizationControls;
    protected DeliveryControlsType deliveryControls;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "IDRef")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object idRef;

    /**
     * Gets the value of the controlMode property.
     *
     * @return possible object is
     *         {@link ControlModeType }
     */
    public ControlModeType getControlMode() {
        return controlMode;
    }

    /**
     * Sets the value of the controlMode property.
     *
     * @param value allowed object is
     *              {@link ControlModeType }
     */
    public void setControlMode(ControlModeType value) {
        this.controlMode = value;
    }

    /**
     * Gets the value of the sequencingRules property.
     *
     * @return possible object is
     *         {@link SequencingRulesType }
     */
    public SequencingRulesType getSequencingRules() {
        return sequencingRules;
    }

    /**
     * Sets the value of the sequencingRules property.
     *
     * @param value allowed object is
     *              {@link SequencingRulesType }
     */
    public void setSequencingRules(SequencingRulesType value) {
        this.sequencingRules = value;
    }

    /**
     * Gets the value of the limitConditions property.
     *
     * @return possible object is
     *         {@link LimitConditionsType }
     */
    public LimitConditionsType getLimitConditions() {
        return limitConditions;
    }

    /**
     * Sets the value of the limitConditions property.
     *
     * @param value allowed object is
     *              {@link LimitConditionsType }
     */
    public void setLimitConditions(LimitConditionsType value) {
        this.limitConditions = value;
    }

    /**
     * Gets the value of the auxiliaryResources property.
     *
     * @return possible object is
     *         {@link AuxiliaryResourcesType }
     */
    public AuxiliaryResourcesType getAuxiliaryResources() {
        return auxiliaryResources;
    }

    /**
     * Sets the value of the auxiliaryResources property.
     *
     * @param value allowed object is
     *              {@link AuxiliaryResourcesType }
     */
    public void setAuxiliaryResources(AuxiliaryResourcesType value) {
        this.auxiliaryResources = value;
    }

    /**
     * Gets the value of the rollupRules property.
     *
     * @return possible object is
     *         {@link RollupRulesType }
     */
    public RollupRulesType getRollupRules() {
        return rollupRules;
    }

    /**
     * Sets the value of the rollupRules property.
     *
     * @param value allowed object is
     *              {@link RollupRulesType }
     */
    public void setRollupRules(RollupRulesType value) {
        this.rollupRules = value;
    }

    /**
     * Gets the value of the objectives property.
     *
     * @return possible object is
     *         {@link ObjectivesType }
     */
    public ObjectivesType getObjectives() {
        return objectives;
    }

    /**
     * Sets the value of the objectives property.
     *
     * @param value allowed object is
     *              {@link ObjectivesType }
     */
    public void setObjectives(ObjectivesType value) {
        this.objectives = value;
    }

    /**
     * Gets the value of the randomizationControls property.
     *
     * @return possible object is
     *         {@link RandomizationType }
     */
    public RandomizationType getRandomizationControls() {
        return randomizationControls;
    }

    /**
     * Sets the value of the randomizationControls property.
     *
     * @param value allowed object is
     *              {@link RandomizationType }
     */
    public void setRandomizationControls(RandomizationType value) {
        this.randomizationControls = value;
    }

    /**
     * Gets the value of the deliveryControls property.
     *
     * @return possible object is
     *         {@link DeliveryControlsType }
     */
    public DeliveryControlsType getDeliveryControls() {
        return deliveryControls;
    }

    /**
     * Sets the value of the deliveryControls property.
     *
     * @param value allowed object is
     *              {@link DeliveryControlsType }
     */
    public void setDeliveryControls(DeliveryControlsType value) {
        this.deliveryControls = value;
    }

    /**
     * Gets the value of the any property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the idRef property.
     *
     * @return possible object is
     *         {@link Object }
     */
    public Object getIDRef() {
        return idRef;
    }

    /**
     * Sets the value of the idRef property.
     *
     * @param value allowed object is
     *              {@link Object }
     */
    public void setIDRef(Object value) {
        this.idRef = value;
    }

}
