//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:19 PM MSD 
//


package org.ieee.ltsc.xsd.lom;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for classification complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="classification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}purpose"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}taxonPath"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}description"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}keyword"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM/extend}customElements"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://ltsc.ieee.org/xsd/LOM/unique}classification"/>
 *       &lt;attGroup ref="{http://ltsc.ieee.org/xsd/LOM/extend}customAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "classification", propOrder = {
        "purposeOrTaxonPathOrDescription"
})
public class Classification {

    @XmlElements({
            @XmlElement(name = "taxonPath", type = TaxonPath.class),
            @XmlElement(name = "description", type = Description.class),
            @XmlElement(name = "keyword", type = Keyword.class),
            @XmlElement(name = "purpose", type = Purpose.class)
    })
    protected List<Object> purposeOrTaxonPathOrDescription;

    /**
     * Gets the value of the purposeOrTaxonPathOrDescription property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the purposeOrTaxonPathOrDescription property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPurposeOrTaxonPathOrDescription().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxonPath }
     * {@link Description }
     * {@link Keyword }
     * {@link Purpose }
     */
    public List<Object> getPurposeOrTaxonPathOrDescription() {
        if (purposeOrTaxonPathOrDescription == null) {
            purposeOrTaxonPathOrDescription = new ArrayList<Object>();
        }
        return this.purposeOrTaxonPathOrDescription;
    }

}
