//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:19 PM MSD 
//


package org.ieee.ltsc.xsd.lom;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Duration complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="Duration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="duration" type="{http://ltsc.ieee.org/xsd/LOM}DurationValue"/>
 *         &lt;element name="description" type="{http://ltsc.ieee.org/xsd/LOM}description"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM/extend}customElements"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Duration", propOrder = {
        "durationOrDescriptionOr"
})
@XmlSeeAlso({
        TypicalLearningTime.class,
        Duration.class
})
public class DataTypesDuration {

    @XmlElements({
            @XmlElement(name = "description", type = Description.class),
            @XmlElement(name = "duration", type = DurationValue.class)
    })
    protected List<Object> durationOrDescriptionOr;

    /**
     * Gets the value of the durationOrDescriptionOr property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the durationOrDescriptionOr property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDurationOrDescriptionOr().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Description }
     * {@link DurationValue }
     */
    public List<Object> getDurationOrDescriptionOr() {
        if (durationOrDescriptionOr == null) {
            durationOrDescriptionOr = new ArrayList<Object>();
        }
        return this.durationOrDescriptionOr;
    }

}
