//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:19 PM MSD 
//


package org.ieee.ltsc.xsd.lom;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for difficultyValues.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;simpleType name="difficultyValues">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="very easy"/>
 *     &lt;enumeration value="easy"/>
 *     &lt;enumeration value="medium"/>
 *     &lt;enumeration value="difficult"/>
 *     &lt;enumeration value="very difficult"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "difficultyValues")
@XmlEnum
public enum DifficultyValues {

    @XmlEnumValue("very easy")
    VERY_EASY("very easy"),
    @XmlEnumValue("easy")
    EASY("easy"),
    @XmlEnumValue("medium")
    MEDIUM("medium"),
    @XmlEnumValue("difficult")
    DIFFICULT("difficult"),
    @XmlEnumValue("very difficult")
    VERY_DIFFICULT("very difficult");
    private final String value;

    DifficultyValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DifficultyValues fromValue(String v) {
        for (DifficultyValues c : DifficultyValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
