//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:19 PM MSD 
//


package org.ieee.ltsc.xsd.lom;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for intendedEndUserRoleValues.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;simpleType name="intendedEndUserRoleValues">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="teacher"/>
 *     &lt;enumeration value="author"/>
 *     &lt;enumeration value="learner"/>
 *     &lt;enumeration value="manager"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "intendedEndUserRoleValues")
@XmlEnum
public enum IntendedEndUserRoleValues {

    @XmlEnumValue("teacher")
    TEACHER("teacher"),
    @XmlEnumValue("author")
    AUTHOR("author"),
    @XmlEnumValue("learner")
    LEARNER("learner"),
    @XmlEnumValue("manager")
    MANAGER("manager");
    private final String value;

    IntendedEndUserRoleValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IntendedEndUserRoleValues fromValue(String v) {
        for (IntendedEndUserRoleValues c : IntendedEndUserRoleValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
