//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:19 PM MSD 
//


package org.ieee.ltsc.xsd.lom;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for interactivityTypeValues.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;simpleType name="interactivityTypeValues">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="active"/>
 *     &lt;enumeration value="expositive"/>
 *     &lt;enumeration value="mixed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "interactivityTypeValues")
@XmlEnum
public enum InteractivityTypeValues {

    @XmlEnumValue("active")
    ACTIVE("active"),
    @XmlEnumValue("expositive")
    EXPOSITIVE("expositive"),
    @XmlEnumValue("mixed")
    MIXED("mixed");
    private final String value;

    InteractivityTypeValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InteractivityTypeValues fromValue(String v) {
        for (InteractivityTypeValues c : InteractivityTypeValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
