//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:19 PM MSD 
//


package org.ieee.ltsc.xsd.lom;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for learningResourceTypeValues.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;simpleType name="learningResourceTypeValues">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="exercise"/>
 *     &lt;enumeration value="simulation"/>
 *     &lt;enumeration value="questionnaire"/>
 *     &lt;enumeration value="diagram"/>
 *     &lt;enumeration value="figure"/>
 *     &lt;enumeration value="graph"/>
 *     &lt;enumeration value="index"/>
 *     &lt;enumeration value="slide"/>
 *     &lt;enumeration value="table"/>
 *     &lt;enumeration value="narrative text"/>
 *     &lt;enumeration value="exam"/>
 *     &lt;enumeration value="experiment"/>
 *     &lt;enumeration value="problem statement"/>
 *     &lt;enumeration value="self assessment"/>
 *     &lt;enumeration value="lecture"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "learningResourceTypeValues")
@XmlEnum
public enum LearningResourceTypeValues {

    @XmlEnumValue("exercise")
    EXERCISE("exercise"),
    @XmlEnumValue("simulation")
    SIMULATION("simulation"),
    @XmlEnumValue("questionnaire")
    QUESTIONNAIRE("questionnaire"),
    @XmlEnumValue("diagram")
    DIAGRAM("diagram"),
    @XmlEnumValue("figure")
    FIGURE("figure"),
    @XmlEnumValue("graph")
    GRAPH("graph"),
    @XmlEnumValue("index")
    INDEX("index"),
    @XmlEnumValue("slide")
    SLIDE("slide"),
    @XmlEnumValue("table")
    TABLE("table"),
    @XmlEnumValue("narrative text")
    NARRATIVE_TEXT("narrative text"),
    @XmlEnumValue("exam")
    EXAM("exam"),
    @XmlEnumValue("experiment")
    EXPERIMENT("experiment"),
    @XmlEnumValue("problem statement")
    PROBLEM_STATEMENT("problem statement"),
    @XmlEnumValue("self assessment")
    SELF_ASSESSMENT("self assessment"),
    @XmlEnumValue("lecture")
    LECTURE("lecture");
    private final String value;

    LearningResourceTypeValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LearningResourceTypeValues fromValue(String v) {
        for (LearningResourceTypeValues c : LearningResourceTypeValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
