//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:19 PM MSD 
//


package org.ieee.ltsc.xsd.lom;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for lom complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="lom">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}general"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}lifeCycle"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}metaMetadata"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}technical"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}educational"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}rights"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}relation"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}annotation"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}classification"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM/extend}customElements"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://ltsc.ieee.org/xsd/LOM/extend}customAttributes"/>
 *       &lt;attGroup ref="{http://ltsc.ieee.org/xsd/LOM/unique}lom"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lom", propOrder = {
        "generalOrLifeCycleOrMetaMetadata"
})
public class Lom {

    @XmlElements({
            @XmlElement(name = "general", type = General.class),
            @XmlElement(name = "classification", type = Classification.class),
            @XmlElement(name = "annotation", type = Annotation.class),
            @XmlElement(name = "lifeCycle", type = LifeCycle.class),
            @XmlElement(name = "technical", type = Technical.class),
            @XmlElement(name = "metaMetadata", type = MetaMetadata.class),
            @XmlElement(name = "educational", type = Educational.class),
            @XmlElement(name = "relation", type = Relation.class),
            @XmlElement(name = "rights", type = Rights.class)
    })
    protected List<Object> generalOrLifeCycleOrMetaMetadata;

    /**
     * Gets the value of the generalOrLifeCycleOrMetaMetadata property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the generalOrLifeCycleOrMetaMetadata property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeneralOrLifeCycleOrMetaMetadata().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Relation }
     * {@link LifeCycle }
     * {@link General }
     * {@link Classification }
     * {@link Rights }
     * {@link MetaMetadata }
     * {@link Educational }
     * {@link Annotation }
     * {@link Technical }
     */
    public List<Object> getGeneralOrLifeCycleOrMetaMetadata() {
        if (generalOrLifeCycleOrMetaMetadata == null) {
            generalOrLifeCycleOrMetaMetadata = new ArrayList<Object>();
        }
        return this.generalOrLifeCycleOrMetaMetadata;
    }

}
