//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:19 PM MSD 
//


package org.ieee.ltsc.xsd.lom;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for nameValues.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;simpleType name="nameValues">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="pc-dos"/>
 *     &lt;enumeration value="ms-windows"/>
 *     &lt;enumeration value="macos"/>
 *     &lt;enumeration value="unix"/>
 *     &lt;enumeration value="multi-os"/>
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="any"/>
 *     &lt;enumeration value="netscape communicator"/>
 *     &lt;enumeration value="ms-internet explorer"/>
 *     &lt;enumeration value="opera"/>
 *     &lt;enumeration value="amaya"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "nameValues")
@XmlEnum
public enum NameValues {

    @XmlEnumValue("pc-dos")
    PC_DOS("pc-dos"),
    @XmlEnumValue("ms-windows")
    MS_WINDOWS("ms-windows"),
    @XmlEnumValue("macos")
    MACOS("macos"),
    @XmlEnumValue("unix")
    UNIX("unix"),
    @XmlEnumValue("multi-os")
    MULTI_OS("multi-os"),
    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("any")
    ANY("any"),
    @XmlEnumValue("netscape communicator")
    NETSCAPE_COMMUNICATOR("netscape communicator"),
    @XmlEnumValue("ms-internet explorer")
    MS_INTERNET_EXPLORER("ms-internet explorer"),
    @XmlEnumValue("opera")
    OPERA("opera"),
    @XmlEnumValue("amaya")
    AMAYA("amaya");
    private final String value;

    NameValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NameValues fromValue(String v) {
        for (NameValues c : NameValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
