//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:19 PM MSD 
//


package org.ieee.ltsc.xsd.lom;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.ieee.ltsc.xsd.lom package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Lom_QNAME = new QName("http://ltsc.ieee.org/xsd/LOM", "lom");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ieee.ltsc.xsd.lom
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CopyrightAndOtherRestrictionsValue }
     */
    public CopyrightAndOtherRestrictionsValue createCopyrightAndOtherRestrictionsValue() {
        return new CopyrightAndOtherRestrictionsValue();
    }

    /**
     * Create an instance of {@link IntendedEndUserRole }
     */
    public IntendedEndUserRole createIntendedEndUserRole() {
        return new IntendedEndUserRole();
    }

    /**
     * Create an instance of {@link DateTime }
     */
    public DateTime createDateTime() {
        return new DateTime();
    }

    /**
     * Create an instance of {@link Entry }
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link PurposeValue }
     */
    public PurposeValue createPurposeValue() {
        return new PurposeValue();
    }

    /**
     * Create an instance of {@link InteractivityTypeValue }
     */
    public InteractivityTypeValue createInteractivityTypeValue() {
        return new InteractivityTypeValue();
    }

    /**
     * Create an instance of {@link Taxon }
     */
    public Taxon createTaxon() {
        return new Taxon();
    }

    /**
     * Create an instance of {@link IntendedEndUserRoleValue }
     */
    public IntendedEndUserRoleValue createIntendedEndUserRoleValue() {
        return new IntendedEndUserRoleValue();
    }

    /**
     * Create an instance of {@link InteractivityLevel }
     */
    public InteractivityLevel createInteractivityLevel() {
        return new InteractivityLevel();
    }

    /**
     * Create an instance of {@link IntendedEndUserRoleVocab }
     */
    public IntendedEndUserRoleVocab createIntendedEndUserRoleVocab() {
        return new IntendedEndUserRoleVocab();
    }

    /**
     * Create an instance of {@link Catalog }
     */
    public Catalog createCatalog() {
        return new Catalog();
    }

    /**
     * Create an instance of {@link DifficultyValue }
     */
    public DifficultyValue createDifficultyValue() {
        return new DifficultyValue();
    }

    /**
     * Create an instance of {@link Contribute }
     */
    public Contribute createContribute() {
        return new Contribute();
    }

    /**
     * Create an instance of {@link DataTypesDuration }
     */
    public DataTypesDuration createDataTypesDuration() {
        return new DataTypesDuration();
    }

    /**
     * Create an instance of {@link LearningResourceType }
     */
    public LearningResourceType createLearningResourceType() {
        return new LearningResourceType();
    }

    /**
     * Create an instance of {@link RoleMetaVocab }
     */
    public RoleMetaVocab createRoleMetaVocab() {
        return new RoleMetaVocab();
    }

    /**
     * Create an instance of {@link Educational }
     */
    public Educational createEducational() {
        return new Educational();
    }

    /**
     * Create an instance of {@link MetaMetadata }
     */
    public MetaMetadata createMetaMetadata() {
        return new MetaMetadata();
    }

    /**
     * Create an instance of {@link SourceValue }
     */
    public SourceValue createSourceValue() {
        return new SourceValue();
    }

    /**
     * Create an instance of {@link Purpose }
     */
    public Purpose createPurpose() {
        return new Purpose();
    }

    /**
     * Create an instance of {@link Annotation }
     */
    public Annotation createAnnotation() {
        return new Annotation();
    }

    /**
     * Create an instance of {@link LearningResourceTypeValue }
     */
    public LearningResourceTypeValue createLearningResourceTypeValue() {
        return new LearningResourceTypeValue();
    }

    /**
     * Create an instance of {@link SemanticDensity }
     */
    public SemanticDensity createSemanticDensity() {
        return new SemanticDensity();
    }

    /**
     * Create an instance of {@link TaxonPath }
     */
    public TaxonPath createTaxonPath() {
        return new TaxonPath();
    }

    /**
     * Create an instance of {@link KindValue }
     */
    public KindValue createKindValue() {
        return new KindValue();
    }

    /**
     * Create an instance of {@link PurposeVocab }
     */
    public PurposeVocab createPurposeVocab() {
        return new PurposeVocab();
    }

    /**
     * Create an instance of {@link RoleValue }
     */
    public RoleValue createRoleValue() {
        return new RoleValue();
    }

    /**
     * Create an instance of {@link ContextValue }
     */
    public ContextValue createContextValue() {
        return new ContextValue();
    }

    /**
     * Create an instance of {@link Keyword }
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link LifeCycle }
     */
    public LifeCycle createLifeCycle() {
        return new LifeCycle();
    }

    /**
     * Create an instance of {@link ContextVocab }
     */
    public ContextVocab createContextVocab() {
        return new ContextVocab();
    }

    /**
     * Create an instance of {@link RoleVocab }
     */
    public RoleVocab createRoleVocab() {
        return new RoleVocab();
    }

    /**
     * Create an instance of {@link RoleMeta }
     */
    public RoleMeta createRoleMeta() {
        return new RoleMeta();
    }

    /**
     * Create an instance of {@link CostVocab }
     */
    public CostVocab createCostVocab() {
        return new CostVocab();
    }

    /**
     * Create an instance of {@link Context }
     */
    public Context createContext() {
        return new Context();
    }

    /**
     * Create an instance of {@link Size }
     */
    public Size createSize() {
        return new Size();
    }

    /**
     * Create an instance of {@link Kind }
     */
    public Kind createKind() {
        return new Kind();
    }

    /**
     * Create an instance of {@link Duration }
     */
    public Duration createDuration() {
        return new Duration();
    }

    /**
     * Create an instance of {@link LanguageId }
     */
    public LanguageId createLanguageId() {
        return new LanguageId();
    }

    /**
     * Create an instance of {@link Cost }
     */
    public Cost createCost() {
        return new Cost();
    }

    /**
     * Create an instance of {@link RoleMetaValue }
     */
    public RoleMetaValue createRoleMetaValue() {
        return new RoleMetaValue();
    }

    /**
     * Create an instance of {@link NameValue }
     */
    public NameValue createNameValue() {
        return new NameValue();
    }

    /**
     * Create an instance of {@link DurationValue }
     */
    public DurationValue createDurationValue() {
        return new DurationValue();
    }

    /**
     * Create an instance of {@link InteractivityLevelValue }
     */
    public InteractivityLevelValue createInteractivityLevelValue() {
        return new InteractivityLevelValue();
    }

    /**
     * Create an instance of {@link TypeValue }
     */
    public TypeValue createTypeValue() {
        return new TypeValue();
    }

    /**
     * Create an instance of {@link MinimumVersion }
     */
    public MinimumVersion createMinimumVersion() {
        return new MinimumVersion();
    }

    /**
     * Create an instance of {@link DateTimeValue }
     */
    public DateTimeValue createDateTimeValue() {
        return new DateTimeValue();
    }

    /**
     * Create an instance of {@link LanguageString }
     */
    public LanguageString createLanguageString() {
        return new LanguageString();
    }

    /**
     * Create an instance of {@link OrComposite }
     */
    public OrComposite createOrComposite() {
        return new OrComposite();
    }

    /**
     * Create an instance of {@link MetadataSchema }
     */
    public MetadataSchema createMetadataSchema() {
        return new MetadataSchema();
    }

    /**
     * Create an instance of {@link CopyrightAndOtherRestrictionsVocab }
     */
    public CopyrightAndOtherRestrictionsVocab createCopyrightAndOtherRestrictionsVocab() {
        return new CopyrightAndOtherRestrictionsVocab();
    }

    /**
     * Create an instance of {@link Location }
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link InstallationRemarks }
     */
    public InstallationRemarks createInstallationRemarks() {
        return new InstallationRemarks();
    }

    /**
     * Create an instance of {@link Version }
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link Title }
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link SemanticDensityVocab }
     */
    public SemanticDensityVocab createSemanticDensityVocab() {
        return new SemanticDensityVocab();
    }

    /**
     * Create an instance of {@link MaximumVersion }
     */
    public MaximumVersion createMaximumVersion() {
        return new MaximumVersion();
    }

    /**
     * Create an instance of {@link InteractivityLevelVocab }
     */
    public InteractivityLevelVocab createInteractivityLevelVocab() {
        return new InteractivityLevelVocab();
    }

    /**
     * Create an instance of {@link SemanticDensityValue }
     */
    public SemanticDensityValue createSemanticDensityValue() {
        return new SemanticDensityValue();
    }

    /**
     * Create an instance of {@link Description }
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Requirement }
     */
    public Requirement createRequirement() {
        return new Requirement();
    }

    /**
     * Create an instance of {@link General }
     */
    public General createGeneral() {
        return new General();
    }

    /**
     * Create an instance of {@link CostValue }
     */
    public CostValue createCostValue() {
        return new CostValue();
    }

    /**
     * Create an instance of {@link AggregationLevelValue }
     */
    public AggregationLevelValue createAggregationLevelValue() {
        return new AggregationLevelValue();
    }

    /**
     * Create an instance of {@link TypeVocab }
     */
    public TypeVocab createTypeVocab() {
        return new TypeVocab();
    }

    /**
     * Create an instance of {@link KindVocab }
     */
    public KindVocab createKindVocab() {
        return new KindVocab();
    }

    /**
     * Create an instance of {@link OtherPlatformRequirements }
     */
    public OtherPlatformRequirements createOtherPlatformRequirements() {
        return new OtherPlatformRequirements();
    }

    /**
     * Create an instance of {@link InteractivityTypeVocab }
     */
    public InteractivityTypeVocab createInteractivityTypeVocab() {
        return new InteractivityTypeVocab();
    }

    /**
     * Create an instance of {@link Id }
     */
    public Id createId() {
        return new Id();
    }

    /**
     * Create an instance of {@link Source }
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link InteractivityType }
     */
    public InteractivityType createInteractivityType() {
        return new InteractivityType();
    }

    /**
     * Create an instance of {@link LangString }
     */
    public LangString createLangString() {
        return new LangString();
    }

    /**
     * Create an instance of {@link Role }
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link VCard }
     */
    public VCard createVCard() {
        return new VCard();
    }

    /**
     * Create an instance of {@link Resource }
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Identifier }
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link DifficultyVocab }
     */
    public DifficultyVocab createDifficultyVocab() {
        return new DifficultyVocab();
    }

    /**
     * Create an instance of {@link Status }
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link Date }
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link TypicalLearningTime }
     */
    public TypicalLearningTime createTypicalLearningTime() {
        return new TypicalLearningTime();
    }

    /**
     * Create an instance of {@link NameVocab }
     */
    public NameVocab createNameVocab() {
        return new NameVocab();
    }

    /**
     * Create an instance of {@link Format }
     */
    public Format createFormat() {
        return new Format();
    }

    /**
     * Create an instance of {@link Rights }
     */
    public Rights createRights() {
        return new Rights();
    }

    /**
     * Create an instance of {@link Entity }
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link Structure }
     */
    public Structure createStructure() {
        return new Structure();
    }

    /**
     * Create an instance of {@link StatusValue }
     */
    public StatusValue createStatusValue() {
        return new StatusValue();
    }

    /**
     * Create an instance of {@link Type }
     */
    public Type createType() {
        return new Type();
    }

    /**
     * Create an instance of {@link Difficulty }
     */
    public Difficulty createDifficulty() {
        return new Difficulty();
    }

    /**
     * Create an instance of {@link Language }
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link StatusVocab }
     */
    public StatusVocab createStatusVocab() {
        return new StatusVocab();
    }

    /**
     * Create an instance of {@link Name }
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link Classification }
     */
    public Classification createClassification() {
        return new Classification();
    }

    /**
     * Create an instance of {@link Technical }
     */
    public Technical createTechnical() {
        return new Technical();
    }

    /**
     * Create an instance of {@link EntryTaxon }
     */
    public EntryTaxon createEntryTaxon() {
        return new EntryTaxon();
    }

    /**
     * Create an instance of {@link Lom }
     */
    public Lom createLom() {
        return new Lom();
    }

    /**
     * Create an instance of {@link StructureValue }
     */
    public StructureValue createStructureValue() {
        return new StructureValue();
    }

    /**
     * Create an instance of {@link StructureVocab }
     */
    public StructureVocab createStructureVocab() {
        return new StructureVocab();
    }

    /**
     * Create an instance of {@link ContributeMeta }
     */
    public ContributeMeta createContributeMeta() {
        return new ContributeMeta();
    }

    /**
     * Create an instance of {@link TypicalAgeRange }
     */
    public TypicalAgeRange createTypicalAgeRange() {
        return new TypicalAgeRange();
    }

    /**
     * Create an instance of {@link AggregationLevel }
     */
    public AggregationLevel createAggregationLevel() {
        return new AggregationLevel();
    }

    /**
     * Create an instance of {@link LearningResourceTypeVocab }
     */
    public LearningResourceTypeVocab createLearningResourceTypeVocab() {
        return new LearningResourceTypeVocab();
    }

    /**
     * Create an instance of {@link AggregationLevelVocab }
     */
    public AggregationLevelVocab createAggregationLevelVocab() {
        return new AggregationLevelVocab();
    }

    /**
     * Create an instance of {@link CopyrightAndOtherRestrictions }
     */
    public CopyrightAndOtherRestrictions createCopyrightAndOtherRestrictions() {
        return new CopyrightAndOtherRestrictions();
    }

    /**
     * Create an instance of {@link Coverage }
     */
    public Coverage createCoverage() {
        return new Coverage();
    }

    /**
     * Create an instance of {@link Relation }
     */
    public Relation createRelation() {
        return new Relation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Lom }{@code >}}
     */
    @XmlElementDecl(namespace = "http://ltsc.ieee.org/xsd/LOM", name = "lom")
    public JAXBElement<Lom> createLom(Lom value) {
        return new JAXBElement<Lom>(_Lom_QNAME, Lom.class, null, value);
    }

}
