//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:19 PM MSD 
//


package org.ieee.ltsc.xsd.lom;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for orComposite complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="orComposite">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}type"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}name"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}minimumVersion"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}maximumVersion"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM/extend}customElements"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://ltsc.ieee.org/xsd/LOM/extend}customAttributes"/>
 *       &lt;attGroup ref="{http://ltsc.ieee.org/xsd/LOM/unique}orComposite"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orComposite", propOrder = {
        "typeOrNameOrMinimumVersion"
})
public class OrComposite {

    @XmlElements({
            @XmlElement(name = "type", type = Type.class),
            @XmlElement(name = "maximumVersion", type = MaximumVersion.class),
            @XmlElement(name = "name", type = Name.class),
            @XmlElement(name = "minimumVersion", type = MinimumVersion.class)
    })
    protected List<Object> typeOrNameOrMinimumVersion;

    /**
     * Gets the value of the typeOrNameOrMinimumVersion property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeOrNameOrMinimumVersion property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeOrNameOrMinimumVersion().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Type }
     * {@link MaximumVersion }
     * {@link Name }
     * {@link MinimumVersion }
     */
    public List<Object> getTypeOrNameOrMinimumVersion() {
        if (typeOrNameOrMinimumVersion == null) {
            typeOrNameOrMinimumVersion = new ArrayList<Object>();
        }
        return this.typeOrNameOrMinimumVersion;
    }

}
