//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:19 PM MSD 
//


package org.ieee.ltsc.xsd.lom;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for roleValues.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;simpleType name="roleValues">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="author"/>
 *     &lt;enumeration value="publisher"/>
 *     &lt;enumeration value="unknown"/>
 *     &lt;enumeration value="initiator"/>
 *     &lt;enumeration value="terminator"/>
 *     &lt;enumeration value="validator"/>
 *     &lt;enumeration value="editor"/>
 *     &lt;enumeration value="graphical designer"/>
 *     &lt;enumeration value="technical implementer"/>
 *     &lt;enumeration value="content provider"/>
 *     &lt;enumeration value="technical validator"/>
 *     &lt;enumeration value="educational validator"/>
 *     &lt;enumeration value="script writer"/>
 *     &lt;enumeration value="instructional designer"/>
 *     &lt;enumeration value="subject matter expert"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "roleValues")
@XmlEnum
public enum RoleValues {

    @XmlEnumValue("author")
    AUTHOR("author"),
    @XmlEnumValue("publisher")
    PUBLISHER("publisher"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),
    @XmlEnumValue("initiator")
    INITIATOR("initiator"),
    @XmlEnumValue("terminator")
    TERMINATOR("terminator"),
    @XmlEnumValue("validator")
    VALIDATOR("validator"),
    @XmlEnumValue("editor")
    EDITOR("editor"),
    @XmlEnumValue("graphical designer")
    GRAPHICAL_DESIGNER("graphical designer"),
    @XmlEnumValue("technical implementer")
    TECHNICAL_IMPLEMENTER("technical implementer"),
    @XmlEnumValue("content provider")
    CONTENT_PROVIDER("content provider"),
    @XmlEnumValue("technical validator")
    TECHNICAL_VALIDATOR("technical validator"),
    @XmlEnumValue("educational validator")
    EDUCATIONAL_VALIDATOR("educational validator"),
    @XmlEnumValue("script writer")
    SCRIPT_WRITER("script writer"),
    @XmlEnumValue("instructional designer")
    INSTRUCTIONAL_DESIGNER("instructional designer"),
    @XmlEnumValue("subject matter expert")
    SUBJECT_MATTER_EXPERT("subject matter expert");
    private final String value;

    RoleValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RoleValues fromValue(String v) {
        for (RoleValues c : RoleValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
