//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:19 PM MSD 
//


package org.ieee.ltsc.xsd.lom;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for technical complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="technical">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}format"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}size"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}location"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}requirement"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}installationRemarks"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}otherPlatformRequirements"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM}duration"/>
 *         &lt;group ref="{http://ltsc.ieee.org/xsd/LOM/extend}customElements"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://ltsc.ieee.org/xsd/LOM/unique}technical"/>
 *       &lt;attGroup ref="{http://ltsc.ieee.org/xsd/LOM/extend}customAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "technical", propOrder = {
        "formatOrSizeOrLocation"
})
public class Technical {

    @XmlElements({
            @XmlElement(name = "duration", type = Duration.class),
            @XmlElement(name = "otherPlatformRequirements", type = OtherPlatformRequirements.class),
            @XmlElement(name = "size", type = Size.class),
            @XmlElement(name = "location", type = Location.class),
            @XmlElement(name = "installationRemarks", type = InstallationRemarks.class),
            @XmlElement(name = "requirement", type = Requirement.class),
            @XmlElement(name = "format", type = Format.class)
    })
    protected List<Object> formatOrSizeOrLocation;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String uniqueElementName;

    /**
     * Gets the value of the formatOrSizeOrLocation property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formatOrSizeOrLocation property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormatOrSizeOrLocation().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Duration }
     * {@link OtherPlatformRequirements }
     * {@link Size }
     * {@link Location }
     * {@link InstallationRemarks }
     * {@link Requirement }
     * {@link Format }
     */
    public List<Object> getFormatOrSizeOrLocation() {
        if (formatOrSizeOrLocation == null) {
            formatOrSizeOrLocation = new ArrayList<Object>();
        }
        return this.formatOrSizeOrLocation;
    }

    /**
     * Gets the value of the uniqueElementName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getUniqueElementName() {
        if (uniqueElementName == null) {
            return "technical";
        } else {
            return uniqueElementName;
        }
    }

    /**
     * Sets the value of the uniqueElementName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUniqueElementName(String value) {
        this.uniqueElementName = value;
    }

}
