//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:20 PM MSD 
//


package org.adlnet.xsd.adlcp_v1p3;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for completionThresholdType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="completionThresholdType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="completedByMeasure" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="minProgressMeasure" type="{http://www.adlnet.org/xsd/adlcp_v1p3}minProgressMeasureType" default="1.0" />
 *       &lt;attribute name="progressWeight" type="{http://www.adlnet.org/xsd/adlcp_v1p3}progressWeightType" default="1.0" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "completionThresholdType", propOrder = {
        "value"
})
public class CompletionThresholdType {

    @XmlValue
    protected String value;
    @XmlAttribute
    protected Boolean completedByMeasure;
    @XmlAttribute
    protected BigDecimal minProgressMeasure;
    @XmlAttribute
    protected BigDecimal progressWeight;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the completedByMeasure property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isCompletedByMeasure() {
        if (completedByMeasure == null) {
            return false;
        } else {
            return completedByMeasure;
        }
    }

    /**
     * Sets the value of the completedByMeasure property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setCompletedByMeasure(Boolean value) {
        this.completedByMeasure = value;
    }

    /**
     * Gets the value of the minProgressMeasure property.
     *
     * @return possible object is
     *         {@link BigDecimal }
     */
    public BigDecimal getMinProgressMeasure() {
        if (minProgressMeasure == null) {
            return new BigDecimal("1.0");
        } else {
            return minProgressMeasure;
        }
    }

    /**
     * Sets the value of the minProgressMeasure property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setMinProgressMeasure(BigDecimal value) {
        this.minProgressMeasure = value;
    }

    /**
     * Gets the value of the progressWeight property.
     *
     * @return possible object is
     *         {@link BigDecimal }
     */
    public BigDecimal getProgressWeight() {
        if (progressWeight == null) {
            return new BigDecimal("1.0");
        } else {
            return progressWeight;
        }
    }

    /**
     * Sets the value of the progressWeight property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setProgressWeight(BigDecimal value) {
        this.progressWeight = value;
    }

}
