//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:20 PM MSD 
//


package org.adlnet.xsd.adlcp_v1p3;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for mapType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="mapType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="targetID" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="readSharedData" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="writeSharedData" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mapType")
public class MapType {

    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String targetID;
    @XmlAttribute
    protected Boolean readSharedData;
    @XmlAttribute
    protected Boolean writeSharedData;

    /**
     * Gets the value of the targetID property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getTargetID() {
        return targetID;
    }

    /**
     * Sets the value of the targetID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTargetID(String value) {
        this.targetID = value;
    }

    /**
     * Gets the value of the readSharedData property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isReadSharedData() {
        if (readSharedData == null) {
            return true;
        } else {
            return readSharedData;
        }
    }

    /**
     * Sets the value of the readSharedData property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setReadSharedData(Boolean value) {
        this.readSharedData = value;
    }

    /**
     * Gets the value of the writeSharedData property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public boolean isWriteSharedData() {
        if (writeSharedData == null) {
            return false;
        } else {
            return writeSharedData;
        }
    }

    /**
     * Sets the value of the writeSharedData property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setWriteSharedData(Boolean value) {
        this.writeSharedData = value;
    }

}
