//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:20 PM MSD 
//


package org.adlnet.xsd.adlcp_v1p3;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.adlnet.xsd.adlcp_v1p3 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Data_QNAME = new QName("http://www.adlnet.org/xsd/adlcp_v1p3", "data");
    private final static QName _Map_QNAME = new QName("http://www.adlnet.org/xsd/adlcp_v1p3", "map");
    private final static QName _TimeLimitAction_QNAME = new QName("http://www.adlnet.org/xsd/adlcp_v1p3", "timeLimitAction");
    private final static QName _DataFromLMS_QNAME = new QName("http://www.adlnet.org/xsd/adlcp_v1p3", "dataFromLMS");
    private final static QName _CompletionThreshold_QNAME = new QName("http://www.adlnet.org/xsd/adlcp_v1p3", "completionThreshold");
    private final static QName _Location_QNAME = new QName("http://www.adlnet.org/xsd/adlcp_v1p3", "location");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.adlnet.xsd.adlcp_v1p3
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MapType }
     */
    public MapType createMapType() {
        return new MapType();
    }

    /**
     * Create an instance of {@link CompletionThresholdType }
     */
    public CompletionThresholdType createCompletionThresholdType() {
        return new CompletionThresholdType();
    }

    /**
     * Create an instance of {@link DataType }
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlcp_v1p3", name = "data")
    public JAXBElement<DataType> createData(DataType value) {
        return new JAXBElement<DataType>(_Data_QNAME, DataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MapType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlcp_v1p3", name = "map")
    public JAXBElement<MapType> createMap(MapType value) {
        return new JAXBElement<MapType>(_Map_QNAME, MapType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeLimitActionType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlcp_v1p3", name = "timeLimitAction")
    public JAXBElement<TimeLimitActionType> createTimeLimitAction(TimeLimitActionType value) {
        return new JAXBElement<TimeLimitActionType>(_TimeLimitAction_QNAME, TimeLimitActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlcp_v1p3", name = "dataFromLMS")
    public JAXBElement<String> createDataFromLMS(String value) {
        return new JAXBElement<String>(_DataFromLMS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompletionThresholdType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlcp_v1p3", name = "completionThreshold")
    public JAXBElement<CompletionThresholdType> createCompletionThreshold(CompletionThresholdType value) {
        return new JAXBElement<CompletionThresholdType>(_CompletionThreshold_QNAME, CompletionThresholdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.adlnet.org/xsd/adlcp_v1p3", name = "location")
    public JAXBElement<String> createLocation(String value) {
        return new JAXBElement<String>(_Location_QNAME, String.class, null, value);
    }

}
