//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 01:06:20 PM MSD 
//


package org.adlnet.xsd.adlcp_v1p3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for timeLimitActionType.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;simpleType name="timeLimitActionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="exit,message"/>
 *     &lt;enumeration value="exit,no message"/>
 *     &lt;enumeration value="continue,message"/>
 *     &lt;enumeration value="continue,no message"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "timeLimitActionType")
@XmlEnum
public enum TimeLimitActionType {

    @XmlEnumValue("exit,message")
    EXIT_MESSAGE("exit,message"),
    @XmlEnumValue("exit,no message")
    EXIT_NO_MESSAGE("exit,no message"),
    @XmlEnumValue("continue,message")
    CONTINUE_MESSAGE("continue,message"),
    @XmlEnumValue("continue,no message")
    CONTINUE_NO_MESSAGE("continue,no message");
    private final String value;

    TimeLimitActionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TimeLimitActionType fromValue(String v) {
        for (TimeLimitActionType c : TimeLimitActionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
